---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: suse:caasp:kube-dns
roleRef:
  kind: ClusterRole
  name: system:kube-dns
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kube-dns
  namespace: kube-system
---
# Allow Kube DNS to use the suse:caasp:psp:privileged
# PodSecurityPolicy.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suse:caasp:psp:kube-dns
roleRef:
  kind: ClusterRole
  name: suse:caasp:psp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kube-dns
  namespace: kube-system
