---
# Map the Dex SA to the Kubernetes cluster-admin role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suse:caasp:dex
roleRef:
  kind: ClusterRole
  name: suse:caasp:dex
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: dex
  namespace: kube-system
---
# Map the LDAP Administrators group to the Kubernetes cluster-admin role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suse:caasp:ldap-administrators
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "{{ pillar['ldap']['admin_group_name'] }}"
  apiGroup: rbac.authorization.k8s.io
---
# Allow Dex to use the suse:caasp:psp:privileged
# PodSecurityPolicy.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suse:caasp:psp:dex
roleRef:
  kind: ClusterRole
  name: suse:caasp:psp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: dex
  namespace: kube-system
